# Generated by Django 4.2.5 on 2023-10-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("foodsearchapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Customization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FoodProductRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="userorder",
            name="items",
        ),
        migrations.RemoveField(
            model_name="userorder",
            name="user",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="food_type",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="is_veg",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="toppings",
        ),
        migrations.AddField(
            model_name="fooditem",
            name="type",
            field=models.CharField(
                choices=[("Veg", "Vegetarian"), ("NonVeg", "Non-Vegetarian")],
                default="Veg",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="FoodType",
        ),
        migrations.DeleteModel(
            name="UserOrder",
        ),
        migrations.AddField(
            model_name="foodproductrating",
            name="food_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foodsearchapp.fooditem"
            ),
        ),
        migrations.AddField(
            model_name="customization",
            name="food_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foodsearchapp.fooditem"
            ),
        ),
        migrations.AddField(
            model_name="customization",
            name="toppings",
            field=models.ManyToManyField(to="foodsearchapp.topping"),
        ),
    ]
