# Generated by Django 4.2.5 on 2023-10-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodsearchapp", "0002_cuisine_customization_foodproductrating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
