# Generated by Django 4.2.5 on 2023-10-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodsearchapp", "0004_product_producttoppings_rating_toppings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
