# Generated by Django 4.2.5 on 2023-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodsearchapp", "0005_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
