# Generated by Django 4.2.5 on 2023-10-02 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodsearchapp", "0007_alter_product_price"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="foodsearchapp_product",
        ),
        migrations.AlterModelTable(
            name="rating",
            table="foodsearchapp_rating",
        ),
    ]
