# Generated by Django 4.2.5 on 2023-10-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodsearchapp", "0008_alter_product_table_alter_rating_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="toppings",
            name="categories",
            field=models.ManyToManyField(
                related_name="toppings", to="foodsearchapp.productcategory"
            ),
        ),
    ]
